api/hacksinepe/src/Neostore.Backend.API/Areas/Admin/Controllers/ReasonsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Neostore.Backend.Domain.Interfaces.Custom;
using Neostore.Backend.Domain.ViewModels.Custom;
using System.Threading.Tasks;

namespace Neostore.Backend.API.Areas.Admin.Controllers
{
    /// <summary>
    /// Manage reasons
    /// </summary>
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ReasonsController : Controller
    {
        IMapper _mapper;
        IReasonService _reasonService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="mapper"></param>
        /// <param name="reasonService"></param>
        public ReasonsController(IMapper mapper,
            IReasonService reasonService)
        {
            _mapper = mapper;
            _reasonService = reasonService;
        }

        /// <summary>
        /// Get list of reasons
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var reasons = await _reasonService.GetAsync();
            
            return View(reasons);
        }

        /// <summary>
        /// Create new reason view page
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Create a new reason
        /// </summary>
        /// <param name="model"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReasonViewModel model)
        {
            if(ModelState.IsValid)
            {
                var reason = await _reasonService.CreateAsync(model);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        /// <summary>
        /// Get reason to update
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var reason = await _reasonService.GetAsync(id);

            return View(reason);
        }

        /// <summary>
        /// Update a reason
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ReasonViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _reasonService.UpdateAsync(id, model);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        /// <summary>
        /// Delete a reason
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int id)
        {
            await _reasonService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

api/hacksinepe/src/Neostore.Backend.API/Areas/Admin/Views/Reasons/Create.cshtml
@model Neostore.Backend.Domain.ViewModels.Custom.ReasonViewModel

@{
    ViewData["Title"] = "Criar nova Razão";
}

<div class="container-fluid container-fixed-lg">
    <ul class="breadcrumb">
        <li><a asp-action="Index" asp-controller="Home">Dashboard</a></li>
        <li><a asp-action="Index" asp-controller="Reasons">Razões</a></li>
        <li><a asp-action="Create" asp-controller="Reasons" class="active">@ViewData["Title"]</a></li>
    </ul>
    <div class="panel panel-transparent">
        <div class="panel-body">
            <form asp-action="Create" asp-controller="Reasons" method="post">
                @Html.Partial("_EditorTemplate")

                <div class="clearfix"></div>
                <div class="col-md-6">
                    <button class="btn btn-success" type="submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

api/hacksinepe/src/Neostore.Backend.API/Areas/Admin/Views/Reasons/Edit.cshtml
@model Neostore.Backend.Domain.ViewModels.Custom.ReasonViewModel

@{
    ViewData["Title"] = "Editar Razão";
}

<div class="container-fluid container-fixed-lg">
    <ul class="breadcrumb">
        <li><a asp-action="Index" asp-controller="Home">Dashboard</a></li>
        <li><a asp-action="Index" asp-controller="Reasons">Razões</a></li>
        <li><a asp-action="Edit" asp-controller="Reasons" asp-route-id="@Model.Id" class="active">@ViewData["Title"]</a></li>
    </ul>
    <div class="panel panel-transparent">
        <div class="panel-body">
            <form asp-action="Edit" asp-controller="Reasons" method="post">
                <input asp-for="@Model.Id" type="hidden" />

                @Html.Partial("_EditorTemplate", Model)

                <div class="clearfix"></div>
                <div class="col-md-6">
                    <button class="btn btn-success" type="submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

api/hacksinepe/src/Neostore.Backend.API/Areas/Admin/Views/Reasons/Index.cshtml
@model IEnumerable<Neostore.Backend.Domain.ViewModels.Custom.ReasonViewModel>
@using Neostore.Backend.Infrastructure.Helpers

@{
    ViewData["Title"] = "Razões";
}

<div class="container-fluid container-fixed-lg">
    <ul class="breadcrumb">
        <li><a asp-action="Index" asp-controller="Home">Dashboard</a></li>
        <li><a asp-action="Index" asp-controller="Reasons" class="active">@ViewData["Title"]</a></li>
    </ul>
    <div class="panel panel-transparent">
        <div class="panel-heading">
            <div class="panel-controls">
                <ul>
                    <li>
                        <a asp-action="Create" asp-controller="Reasons" class="btn btn-info"><i class="fa fa-plus"></i> Novo</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="panel-body">
            <table class="table table-hover table-condensed" id="reasons-table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Descrição</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Description</td>
                            <td>
                                <div class="btn-group">
                                    <a asp-action="Edit" asp-controller="Reasons" asp-route-id="@item.Id" class="btn btn-default">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button data-toggle="modal" data-target="#modalDelete@(item.Id)" type="button" class="btn btn-default">
                                        <i class="fa fa-remove"></i>
                                    </button>
                                    <div class="modal fade slide-up disable-scroll" id="modalDelete@(item.Id)" tabindex="-1" role="dialog" aria-hidden="false">
                                        <div class="modal-dialog ">
                                            <div class="modal-content-wrapper">
                                                <div class="modal-content">
                                                    <div class="modal-header clearfix text-center">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                            <i class="pg-close fs-14"></i>
                                                        </button>
                                                        <h5><span class="semi-bold">Confirmar Exclusão</span></h5>
                                                        <p class="p-b-10">Tem certeza que deseja excluir esse registro?</p>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="row">
                                                            <div class="col-sm-6 m-t-6 sm-m-t-6">
                                                                <button type="button" class="btn btn-default btn-block m-t-5" data-dismiss="modal">Cancelar</button>
                                                            </div>
                                                            <div class="col-sm-6 m-t-6 sm-m-t-6">
                                                                <a asp-action="Delete" asp-controller="Reasons" asp-route-id="@item.Id" class="btn btn-danger btn-block m-t-5">Excluir</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts{
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>

    <script>
        $(document).ready(function () {
            var table = $('#reasons-table');

            var settings = {
                "dom": 'rtip',
                "order": [[0, "asc"]],
                "destroy": true,
                "scrollCollapse": true,
                "oLanguage": {
                    "sLengthMenu": "_MENU_ ",
                    "sInfo": "Mostrando <b>_START_ a _END_</b> de _TOTAL_ registros"
                },
                "iDisplayLength": 10,
            };

            table.dataTable(settings);
        });
    </script>
}

api/hacksinepe/src/Neostore.Backend.API/Areas/Admin/Views/Reasons/_EditorTemplate.cshtml
@model Neostore.Backend.Domain.ViewModels.Custom.ReasonViewModel

@{
    Layout = null;
}

<div class="col-md-6">
    <div class="form-group form-group-default required">
        <label asp-for="@Model.Description"></label>
        <input type="text" asp-for="@Model.Description" class="form-control" required="required">
    </div>
</div>