api/hacksinepe/src/Neostore.Backend.API/Areas/Admin/Controllers/EvaluationsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Neostore.Backend.Domain.Models.Context;
using Neostore.Backend.Domain.Models.Users;
using Neostore.Backend.Domain.ViewModels.Custom;
using Neostore.Backend.Infrastructure.Extensions;
using System.Linq;

namespace Neostore.Backend.API.Areas.Admin.Controllers
{
    /// <summary>
    /// Evaluations manager
    /// </summary>
    [Area("Admin")]
    [Authorize(Roles = "Admin, Seller")]
    public class EvaluationsController : Controller
    {
        BackendContext _context;
        IMapper _mapper;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        /// <param name="mapper"></param>
        public EvaluationsController(BackendContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        /// <summary>
        /// Get evaluation list
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var returnAll = _context.Users
                .OfType<AdminUser>()
                .Any(u => u.Id == User.GetUserId());
            
            var evaluations = _context.Evaluations
                .Where(e => e.Seller.Id == User.GetUserId() || returnAll)
                .Include(e => e.Buyer)
                .Include(e => e.Seller)
                .Include(e => e.EvaluationReasons)
                    .ThenInclude(e => e.Reason)
                .ToList();

            var model = evaluations
                .Select(e => _mapper.Map<EvaluationViewModel>(e))
                .ToList();

            foreach (var item in model)
            {
                foreach (var evaluationReason in item.EvaluationReasons)
                {
                    item.Reasons.Add(_mapper.Map<ReasonViewModel>(evaluationReason.Reason));
                }
            }

            model = model.OrderByDescending(m => m.CreateDate).ToList();

            return View(model);
        }
    }
}

api/hacksinepe/src/Neostore.Backend.API/Areas/Admin/Views/Evaluations/Index.cshtml
@model IEnumerable<Neostore.Backend.Domain.ViewModels.Custom.EvaluationViewModel>
@using Neostore.Backend.Infrastructure.Helpers

@{
    ViewData["Title"] = "Avaliações";
}

<div class="container-fluid container-fixed-lg">
        <ul class="breadcrumb">
            <li><a asp-action="Index" asp-controller="Home">Dashboard</a></li>
            <li><a asp-action="Index" asp-controller="Evaluations" class="active">Avaliações</a></li>
        </ul>
        <div class="panel panel-transparent">
            <div class="panel-body">
                <table class="table table-hover" id="evaluations-table">
                    <thead>
                        <tr>
                            <th>Loja</th>
                            <th>Data</th>
                            <th>Hora</th>
                            <th>Nota</th>
                            <th>O que pode melhorar?</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            @if (item.Reasons.Count == 0)
                            {
                                <tr>
                                    <td>@($"{item?.Seller?.FirstName} {item?.Seller?.LastName}")</td>
                                    <td>@item.CreateDate.ToLocal().ToString("dd/MM/yyyy")</td>
                                    <td>@item.CreateDate.ToLocal().ToString("HH:mm:ss")</td>
                                    <td>@item.Rating</td>
                                    <td>Não selecionado</td>
                                </tr>
                            }
                            @foreach (var reason in item.Reasons)
                            {
                                <tr>
                                    <td>@($"{item?.Seller?.FirstName} {item?.Seller?.LastName}")</td>
                                    <td>@item.CreateDate.ToLocal().ToString("dd/MM/yyyy")</td>
                                    <td>@item.CreateDate.ToLocal().ToString("HH:mm:ss")</td>
                                    <td>@item.Rating</td>
                                    <td>@reason.Description</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
</div>

@section scripts{
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="//cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.13/i18n/Portuguese-Brasil.json"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.13/sorting/datetime-moment.js"></script>

    <script>
        $(document).ready(function () {
            $.fn.dataTable.moment('DD/MM/YYYY');

            var table = $('#evaluations-table');

            var settings = {
                "dom": 'Brtip',
                "order": [[ 1, "desc" ], [2, "desc"]],
                "destroy": true,
                "scrollCollapse": true,
                "iDisplayLength": 10,
                "buttons" : [
                    'copyHtml5',
                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5'
                ],
                fnDrawCallback: function (oSettings) {
                    $('.export-options-container').append($('.exportOptions'));

                    $('.buttons-csv').tooltip({
                        title: 'Exportar como CSV',
                        container: 'body'
                    });

                    $('.buttons-excel').tooltip({
                        title: 'Exportar como Excel',
                        container: 'body'
                    });

                    $('.buttons-pdf').tooltip({
                        title: 'Exportar como PDF',
                        container: 'body'
                    });

                    $('.buttons-copy').tooltip({
                        title: 'Copiar dados',
                        container: 'body'
                    });
                }
            };

            table.dataTable(settings);

            $(".dt-buttons").addClass("btn-group");
            $(".dt-buttons").addClass("pull-right");

            $('.dt-button').each(function (i, obj) {
                $(this).addClass("btn");
                $(this).addClass("btn-default");
            });

            $(".buttons-copy").html('<i class="fa fa-copy"></i> Copiar');
            $(".buttons-excel").html('<i class="fa fa-file-excel-o"></i> Excel');
            $(".buttons-csv").html('<i class="fa fa-file-text-o"></i> CSV');
            $(".buttons-pdf").html('<i class="fa fa-file-pdf-o"></i> PDF');
        });
    </script>
}