api/hacksinepe/src/Neostore.Backend.API/Controllers/LikesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Neostore.Backend.Domain.Models;
using Neostore.Backend.Domain.Models.Context;
using Neostore.Backend.Infrastructure.Extensions;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Neostore.Backend.API.Controllers
{
    /// <summary>
    /// Manage likes
    /// </summary>
    [Route("api/[controller]")]
    [Authorize]
    public class LikesController : Controller
    {
        BackendContext _context;

        /// <summary>
        /// Constructor
        /// </summary>
        public LikesController(BackendContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Create likes
        /// </summary>
        /// <returns></returns>
        [HttpPost("{contentId}")]
        public async Task<IActionResult> Post(int contentId)
        {
            try
            {
                _context.Likes.Add(new Like
                {
                    Content = _context.Contents.FirstOrDefault(c => c.Id == contentId),
                    Owner = _context.Users.FirstOrDefault(u => u.Id == User.GetUserId()),
                    IsLike = true
                });

                await _context.SaveChangesAsync();

                return Created("", null);
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
        }
    }
}

api/hacksinepe/src/Neostore.Backend.API/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}

<div class="container-fluid container-fixed-lg footer">
    <div class="copyright sm-text-center">
        <p class="small no-margin pull-left sm-pull-reset">
            <span class="hint-text">Copyright &copy; 2017 </span>
            <span class="font-montserrat">Neostore</span>.
            <span class="hint-text">Todos os direitos reservados. </span>
        </p>
        <div class="clearfix"></div>
    </div>
</div>

api/hacksinepe/src/Neostore.Backend.API/Views/Shared/_Header.cshtml
@{
    Layout = null;
}

<div class="header ">
    <!-- START MOBILE CONTROLS -->
    <div class="container-fluid relative">
        <!-- LEFT SIDE -->
        <div class="pull-left full-height visible-sm visible-xs">
            <!-- START ACTION BAR -->
            <div class="header-inner">
                <a href="#" class="btn-link toggle-sidebar visible-sm-inline-block visible-xs-inline-block padding-5" data-toggle="sidebar">
                    <span class="icon-set menu-hambuger"></span>
                </a>
            </div>
            <!-- END ACTION BAR -->
        </div>
        <div class="pull-center hidden-md hidden-lg">
            <div class="header-inner">
                <div class="brand inline">
                    <img src="~/assets/img/logo.png" alt="logo" data-src="@Url.Content("~/assets/img/logo.png")" data-src-retina="@Url.Content("~/assets/img/logo.png")" 
                         width="78" height="60">
                </div>
            </div>
        </div>
        <!-- RIGHT SIDE -->
        <div class="pull-right full-height visible-sm visible-xs">
            <!-- START ACTION BAR -->
            <div class="header-inner">
                <a href="#" class="btn-link visible-sm-inline-block visible-xs-inline-block" data-toggle="quickview" data-toggle-element="#quickview">
                    <span class="icon-set menu-hambuger-plus"></span>
                </a>
            </div>
            <!-- END ACTION BAR -->
        </div>
    </div>
    <!-- END MOBILE CONTROLS -->
    <div class=" pull-left sm-table hidden-xs hidden-sm">
        <div class="header-inner">
            <div class="brand inline">
                <img src="~/assets/img/logo.png" alt="logo" data-src="@Url.Content("~/assets/img/logo.png")" data-src-retina="@Url.Content("~/assets/img/logo.png")" 
                     height="60">
            </div>
        </div>
    </div>
    <div class="pull-right">
        <!-- START User Info-->
        <div class="visible-lg visible-md m-t-10">
            <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
                <span class="semi-bold">@User.GetFirstName()?.Result</span> <span class="text-master">@User.GetLastName()?.Result</span>
            </div>
            <div class="dropdown pull-right">
                <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="thumbnail-wrapper d32 circular inline m-t-5">
                        <i class="pg-more"></i>
                    </span>
                </button>
                <ul class="dropdown-menu profile-dropdown" role="menu">
                    <li class="bg-master-lighter">
                        <a asp-action="Logoff" asp-controller="Account" asp-area="" class="clearfix">
                            <span class="pull-left">Logout</span>
                            <span class="pull-right"><i class="pg-power"></i></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- END User Info-->
    </div>
</div>

api/hacksinepe/src/Neostore.Backend.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title - WeLike | Weee</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <link rel="apple-touch-icon" href="~/pages/ico/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/pages/ico/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/pages/ico/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/pages/ico/152.png">
    <link rel="icon" type="image/x-icon" href="~/assets/img/favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link class="main-stylesheet" href="~/output/css/site.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="fixed-header">
    @Html.Partial("_Sidebar")
    @Html.Partial("_Header")
    <div class="page-container">
        <div class="page-content-wrapper ">
            <div class="content">
                <div class="jumbotron" data-pages="parallax">
                    @RenderBody()
                </div>
            </div>
            @Html.Partial("_Footer")
        </div>
    </div>
    <script src="~/output/js/site.min.js" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

api/hacksinepe/src/Neostore.Backend.API/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Encantômetro | Neostore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <link rel="apple-touch-icon" href="~/pages/ico/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/pages/ico/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/pages/ico/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/pages/ico/152.png">
    <link rel="icon" type="image/x-icon" href="~/assets/img/favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link class="main-stylesheet" href="~/output/css/site.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        window.onload = function () {
            // fix for windows 8
            if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
                document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
        }
    </script>
</head>
<body class="fixed-header">
    @RenderBody()
    <script src="~/output/js/site.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $('#form-login').validate()
        })
    </script>
</body>
</html>

api/hacksinepe/src/Neostore.Backend.API/Views/Shared/_Sidebar.cshtml
@using Neostore.Backend.Infrastructure.Extensions

@{
    Layout = null;
}

<nav class="page-sidebar" data-pages="sidebar">
    <div class="sidebar-header">
        <img src="~/assets/img/logo.png" alt="logo" data-src="@Url.Content("~/assets/img/logo.png")" data-src-retina="@Url.Content("~/assets/img/logo.png")" height="60">
    </div>
    <div class="sidebar-menu">
        <ul class="menu-items">
            @if (User.Identity.IsAuthenticated)
            {
                @if (User.IsInRole("Admin"))
                {
                    <li class="m-t-30 ">
                        <a asp-action="Index" asp-controller="Home" class="detailed">
                            <span class="title">Dashboard</span>
                            <span class="details">Resumo geral</span>
                        </a>
                        <span class="icon-thumbnail @(Html.IsCurrentController("Home") ? "bg-success" : "")">
                            <i class="pg-home"></i>
                        </span>
                    </li>
                }
                <li class="">
                    <a asp-action="Index" asp-controller="Likes" class="detailed">
                        <span class="title">Conteúdos</span>
                        <span class="details">Sugestão de alunos</span>
                    </a>
                    <span class="icon-thumbnail @(Html.IsCurrentController("Likes") ? "bg-success" : "")">
                        <i class="fa fa-comments"></i>
                    </span>
                </li>
            }
        </ul>
        <div class="clearfix"></div>
    </div>
</nav>